[tool.poetry]
name = "opennem-backend"
version = "3.16.12a4"
description = "OpenNEM Australian Energy Data Backend"
authors = ["Dylan McConnell <dylan.mcconnell@unimelb.edu.au>", "Nik Cubrilovic <nik@infotorch.org>"]
packages = [
    { include = "opennem" }
]

[project]
license = "MIT"
readme = "README.md"
homepage = "https://opennem.org.au"
repository = "https://github.com/opennem/opennem"
keywords = ["opennem", "analysis", "australia", "energy"]
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Environment :: Console",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3.10",
  "Topic :: Scientific/Engineering"
]
include = [
  'README.md'
]
dynamic = ["version"]

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.23.0"
sentry-sdk = "^1.15.0"
pydantic = {extras = ["email"], version = "^1.8.2"}
alembic = "^1.6.2"
click = "^8.0.3"
huey = "^2.2.0"
redis = "^4.3.4"
openpyxl = "^3.0.4"
geojson = "^2.5.0"
fastapi = "^0.95.0"
shapely = "^2.0.2"
python-dotenv = "^1.0.0"
geojson-pydantic = "^0.4.2"
validators = "^0.18.1"
python-magic = "^0.4.18"
cachetools = "^5.0.0"
xlrd = "^2.0.1"
datetime-truncate = "^1.1.1"
datedelta = "^1.3"
pandas = "2.1.4"
osm2geojson = "^0.2.0"
Mako = "^1.1.4"
SQLAlchemy = "^1.4.15"
requests-cache = "^0.9.1"
gitignore-parser = "^0.0.8"
rich = "^12.2.0"
GeoAlchemy2 = "^0.13.1"
boto3 = "^1.23.7"
pyquery = "^2.0.0"
seaborn = "^0.12.0"
fastapi-cache2 = {extras = ["redis"], version = "^0.2.1"}
httpx = {extras = ["brotli"], version = "^0.23.3"}
psycopg2-binary = "^2.9.5"
uvicorn = "^0.22.0"
result = "^0.10.0"
gunicorn = "^21.2.0"


[tool.poetry.group.dev.dependencies]
black = "^23.1.0"
rope = "^1.0.0"
pytest = "^7.0.1"
pytest-watch = "^4.2.0"
mypy = "^1.0.0"
mdutils = "^1.2.2"
sqlalchemy-stubs = "^0.4"
pytest-benchmark = "^4.0.0"
GitPython = "^3.1.12"
pdbpp = "^0.10.2"
pytest-sugar = "^0.9.4"
tox = "^4.2.6"
types-requests = "^2.25.2"
betamax = "^0.8.1"
types-python-dateutil = "^2.8.0"
coverage = "^7.1.0"
pytest-cov = "^4.0.0"
types-cachetools = "^5.0.0"
types-PyYAML = "^6.0.4"
freezegun = "^1.2.2"
pyright = "^1.1.299"
ruff = "^0.1.14"
hatch = "^1.7.0"
pre-commit = "^3.7.1"

[tool.poetry.scripts]
opennem = 'opennem.cli:main'

[tool.poetry.extras]
postgres = ["psycopg2"]

[tool.ruff]
target-version = "py311"
line-length = 130
lint.select = [
  "E",  # pycodestyle errors
  "W",  # pycodestyle warnings
  "F",  # pyflakes
  "I",  # isort
  "C",  # flake8-comprehensions
  "B",  # flake8-bugbear
  "UP", # pyupgrade
]
lint.ignore = [
    "E501",  # line too long, handled by black
    "B008",  # do not perform function calls in argument defaults
    "C901",  # too complex
    "E721",  # do not compare types, use 'isinstance()'
]
exclude = [
  ".git",
  ".venv",
  "var",
  "scripts",
  "opennem/db/migrations",
  "build",
  "notebooks",
  "opennem/stubs",
  ".ipython",
  ".jupyter",
]

[tool.black]
line-length = 130
target_version = ['py311']
include = '\.pyi?$'
exclude = '''
/(\.git/
  |\.eggs
  |__pycache__
  |\.cache
  |\.ipynb_checkpoints
  |\.mypy_cache
  |\.pytest_cache
  |\.tox
  |\.venv
  |node_modules
  |_build
  |buck-out
  |build
  |dist
  |media
  |infrastructure
  |templates
  |locale
)/
'''

[tool.mypy]
python_version = "3.11"
plugins = "sqlmypy,pydantic.mypy"
ignore_missing_imports = true
disallow_untyped_defs = true
pretty = true
show_column_numbers = true
show_error_codes = true
show_error_context = true

[tool.pyright]
include = ["opennem/**/*.py"]
exclude = ["opennem/db/migrations/env.py"]
python_version = "3.11"
reportMissingImports = "error"
reportMissingTypeStubs = false

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
